'use client';

import { useMemo, useState } from 'react';
import { ArrowRight, Bot, Check, ChevronRight, CloudRain, Compass, Heart, MapPinned, Menu, Send, Sparkles, Star, Wallet, X } from 'lucide-react';
import { demoAlternatives as plans, demoDimensions as dimensions, type Choice } from '@/lib/travel';
export default function Home() {
 const [menu, setMenu] = useState(false); const [demo, setDemo] = useState(false); const [disrupted, setDisrupted] = useState(false); const [selected, setSelected] = useState<Choice | null>(null); const [feedback, setFeedback] = useState(false); const [twin, setTwin] = useState(false); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState(''); const [twinReply, setTwinReply] = useState('“I\'ve kept your love of local stories and rainy-day comfort in mind.”');
 const active = selected ? plans[selected] : null; const pulse = active ? active.score : disrupted ? 61 : 91; const estimated = 1240 + (active ? active.cost - 35 : 0);
 const pulseLabel = useMemo(() => active ? 'Recovered' : disrupted ? 'Needs attention' : 'In sync', [active, disrupted]);
 const chooseAlternative = async (choice: Choice) => { setSaving(true); setNotice(''); try { const response = await fetch('/api/journey/replan', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ choice }) }); if (!response.ok) throw new Error('Replanning is temporarily unavailable.'); setSelected(choice); setDisrupted(true); } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to update the journey.'); } finally { setSaving(false); } };
 const sendFeedback = async () => { setSaving(true); setNotice(''); try { const response = await fetch('/api/feedback', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ rating: 'positive' }) }); if (!response.ok) throw new Error('Feedback could not be saved.'); setFeedback(true); } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to save feedback.'); } finally { setSaving(false); } };
 const askTwin = async () => { setSaving(true); setNotice(''); try { const response = await fetch('/api/twin', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message: 'How should I adapt my route?' }) }); const data = await response.json() as { reply?: string; error?: string }; if (!response.ok || !data.reply) throw new Error(data.error ?? 'Your Travel Twin is unavailable.'); setTwinReply(`“${data.reply}”`); } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to reach your Travel Twin.'); } finally { setSaving(false); } };
 return <main>
  <nav><a className="brand" href="#top"><Compass size={22}/> travelmate<span>360</span></a><div className={menu ? 'links open' : 'links'}><a href="#dna">Travel DNA</a><a href="#journey">Journeys</a><a href="#pulse">Journey Pulse</a><button className="ghost" onClick={() => setTwin(true)}>Meet your Twin</button></div><button className="menu" onClick={() => setMenu(!menu)} aria-label="menu">{menu ? <X/> : <Menu/>}</button><button className="nav-demo" onClick={() => setDemo(true)}>Try demo <ArrowRight size={15}/></button></nav>
  <section id="top" className="hero"><div className="hero-copy"><p className="eyebrow"><Sparkles size={14}/> PERSONALIZED TRAVEL INTELLIGENCE</p><h1>Your journey, <i>alive</i> with possibility.</h1><p className="lead">A travel companion that understands what moves you, plans beautifully, and adapts when the world changes.</p><div className="actions"><button className="primary" onClick={() => setDemo(true)}>Start your demo journey <ArrowRight size={17}/></button><a className="text-link" href="#dna">Explore the intelligence <ChevronRight size={17}/></a></div><p className="data-note">Demo Mode • No account or API key required</p></div><div className="passport"><div className="passport-top"><span>TRAVEL DNA</span><Heart size={16}/></div><div className="orb">✦</div><h3>Curious Culture Seeker</h3><p>Tokyo · 3 days</p><div className="chips"><span>92% Culture</span><span>86% Discovery</span></div><div className="mini-route"><MapPinned size={16}/><span>Shibuya</span><b>→</b><span>Asakusa</span><b>→</b><span>Yanaka</span></div></div></section>
  <section id="dna" className="section dna"><div><p className="eyebrow">01 / KNOW YOURSELF</p><h2>Travel DNA, beyond preferences.</h2><p>Our adaptive profile turns your tastes, energy, and values into a living travel signal. Every recommendation explains its match.</p><button className="secondary" onClick={() => setDemo(true)}>View demo profile <ArrowRight size={16}/></button></div><div className="dna-card"><div className="card-head"><span>ARJUN&apos;S TRAVEL DNA</span><b>Updated today</b></div>{dimensions.map(d => <div className="dimension" key={d.label}><span>{d.label}</span><div><i style={{width: `${d.value}%`, background: d.color}}/></div><b>{d.value}</b></div>)}<p className="insight"><Sparkles size={15}/> Your strongest signal: meaningful local stories.</p></div></section>
  <section id="journey" className="journey section"><p className="eyebrow">02 / PLAN WITH INTENT</p><h2>An itinerary that feels like <i>you.</i></h2><div className="timeline"><article><span className="day">DAY 1</span><h3>Old Tokyo, new perspective</h3><p>Asakusa · Yanaka · Kappabashi</p><div className="time"><b>09:00</b><span>Senso-ji dawn walk <em>94% AI match</em></span></div><div className="time"><b>12:30</b><span>Family-run soba lunch <em>88% AI match</em></span></div></article><article className={active ? 'changed' : disrupted ? 'risk' : ''}><span className="day">DAY 2</span><h3>{active ? active.name : 'Modern Tokyo & art'}</h3><p>{active ? 'Replanned itinerary · ' + active.note : 'Shibuya · Roppongi · Daikanyama'}</p><div className="time"><b>11:00</b><span>{active ? 'Updated route · ¥' + active.cost : 'TeamLab Borderless <em>91% AI match</em>'}</span></div><div className="time"><b>16:00</b><span>{active ? 'Pulse restored to ' + active.score : 'Tokyo City View <em>86% AI match</em>'}</span></div></article><article><span className="day">DAY 3</span><h3>Design, flavor, farewell</h3><p>Kiyosumi · Ginza · Shinjuku</p><div className="time"><b>10:00</b><span>Design stores & coffee <em>89% AI match</em></span></div></article></div></section>
  <section id="pulse" className="pulse section"><div className="pulse-main"><p className="eyebrow">03 / STAY IN THE MOMENT</p><h2>Journey Pulse</h2><p>Your travel health, continuously balanced across joy, logistics, weather, and spending.</p><div className="score"><strong>{pulse}</strong><span>/100<br/><b>{pulseLabel}</b></span></div><div className="factors"><span>Experience <b>{active ? 92 : disrupted ? 58 : 93}</b></span><span>Logistics <b>{active ? 86 : disrupted ? 65 : 88}</b></span><span>Budget <b>{active ? 89 : 91}</b></span></div></div><div className="pulse-event">{!disrupted ? <><div className="sun">☀</div><p className="tag">LIVE-STYLE DEMO DATA</p><h3>Your day is beautifully on track.</h3><p>Clear skies, short travel times, and your favorite kind of discovery.</p><button className="secondary" onClick={() => setDisrupted(true)}><CloudRain size={17}/> Simulate a rainy disruption</button></> : <><CloudRain size={36}/><p className="tag risk-text">SIMULATED SCENARIO</p><h3>Heavy rain changes your afternoon.</h3><p>Tokyo City View is closing early. Your pace and experience scores have dropped.</p><button className="primary" onClick={() => document.getElementById('replan')?.scrollIntoView({behavior:'smooth'})}>See smart alternatives <ArrowRight size={16}/></button></>}</div></section>
  <section id="replan" className="replan section"><p className="eyebrow">04 / ADAPT INTELLIGENTLY</p><h2>Change plans, not the feeling.</h2><p className="sub">When a moment shifts, your Travel Twin makes the trade-offs clear. <b>All recommendations below are Demo Data.</b></p><div className="alternatives">{(Object.keys(plans) as Choice[]).map((key, i) => { const p=plans[key]; return <article className={selected===key ? 'option selected' : 'option'} key={key}><p className="option-label">{i===0?'✦ BEST AI MATCH':i===1?'◌ BEST HIDDEN GEM':'¥ BEST BUDGET CHOICE'}</p><h3>{p.name}</h3><p>{p.note}</p><div><span><Star size={14} fill="currentColor"/> {p.score}% match</span><span><Wallet size={14}/> ¥{p.cost}</span></div><button disabled={saving} onClick={() => void chooseAlternative(key)}>{selected===key ? <><Check size={16}/> Added to journey</> : saving ? 'Updating…' : 'Choose this alternative'}</button></article>})}</div>{active && <div className="update"><Check size={19}/><div><b>Day 2 has been updated.</b><p>{active.name} replaces Tokyo City View. Route adjusted, ¥{Math.abs(active.cost-35)} {active.cost>35?'added':'saved'}, and Journey Pulse recovered to {active.score}.</p></div></div>}</section>
  <section className="budget section"><div><p className="eyebrow">TRAVEL WITH CLARITY</p><h2>Every yen has a story.</h2><p>Track what you&apos;re spending, what&apos;s estimated, and how a change affects your trip.</p></div><div className="budget-card"><p>TRIP BUDGET <span>ESTIMATED DATA</span></p><strong>¥{estimated.toLocaleString()}</strong><small>of ¥1,500,000 planned</small><div className="bar"><i style={{width:`${estimated/15000}%`}}/></div><div className="budget-grid"><span>Stay <b>¥540</b></span><span>Experiences <b>¥{active ? 260+active.cost : 295}</b></span><span>Food <b>¥310</b></span><span>Transit <b>¥130</b></span></div></div></section>
  <section className="memories"><div><p className="eyebrow">YOUR STORY, KEPT</p><h2>Journeys become memories.</h2><p>Save the small discoveries, revisit completed journeys, and let the next adventure start wiser.</p></div><div className="memory-card"><span>KYOTO · SPRING 2025</span><h3>Quiet temples,<br/>loud memories.</h3><p>12 saved moments · 4.8 traveller rating</p><button>Open journal <ArrowRight size={15}/></button></div></section>
  <footer><a className="brand" href="#top"><Compass size={20}/> travelmate<span>360</span></a><p>Your Journey. Your DNA. Reimagined by AI.</p><span>Demo experience · Simulated data is clearly labelled</span></footer>
  {demo && <div className="modal-wrap" role="dialog" aria-modal="true"><div className="modal"><button className="close" onClick={() => setDemo(false)}><X/></button><p className="eyebrow">SKILL EXPO DEMO JOURNEY</p><h2>Your 3-minute intelligence loop</h2><ol><li><b>Travel DNA</b><span>Meet Arjun, a Curious Culture Seeker.</span></li><li><b>AI Itinerary</b><span>Explore a personal three-day Tokyo route.</span></li><li><b>Journey Pulse</b><span>Simulate rain and see what changed.</span></li><li><b>Dynamic Replanning</b><span>Choose an alternative and recover the day.</span></li><li><b>Feedback</b><span>Teach the profile what mattered.</span></li></ol><button className="primary" onClick={() => {setDemo(false); document.getElementById('dna')?.scrollIntoView({behavior:'smooth'})}}>Begin the journey <ArrowRight size={17}/></button></div></div>}
  {twin && <div className="twin"><button onClick={() => setTwin(false)} aria-label="Close Travel Twin"><X size={16}/></button><Bot size={22}/><b>Aria, your Travel Twin</b><p>{twinReply}</p><button className="chat" disabled={saving} onClick={() => void askTwin()}>Ask about this route <Send size={14}/></button></div>}
  {notice && <p className="api-notice" role="status">{notice}</p>}
  <button className="feedback" disabled={saving} onClick={() => void sendFeedback()}>{feedback ? <><Check size={16}/> DNA updated: comfort +2</> : <>How was this change? <Heart size={16}/></>}</button>
 </main>
}
